# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 199)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.oFrameMain = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oFrameMain.sizePolicy().hasHeightForWidth())
        self.oFrameMain.setSizePolicy(sizePolicy)
        self.oFrameMain.setMinimumSize(QtCore.QSize(530, 160))
        self.oFrameMain.setMaximumSize(QtCore.QSize(530, 160))
        self.oFrameMain.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.oFrameMain.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.oFrameMain.setFrameShadow(QtWidgets.QFrame.Raised)
        self.oFrameMain.setObjectName("oFrameMain")
        self.oLbEthernet = QtWidgets.QLabel(self.oFrameMain)
        self.oLbEthernet.setGeometry(QtCore.QRect(20, 0, 311, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oLbEthernet.sizePolicy().hasHeightForWidth())
        self.oLbEthernet.setSizePolicy(sizePolicy)
        self.oLbEthernet.setMinimumSize(QtCore.QSize(300, 30))
        self.oLbEthernet.setMaximumSize(QtCore.QSize(500, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oLbEthernet.setFont(font)
        self.oLbEthernet.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.oLbEthernet.setFrameShape(QtWidgets.QFrame.Box)
        self.oLbEthernet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.oLbEthernet.setAlignment(QtCore.Qt.AlignCenter)
        self.oLbEthernet.setObjectName("oLbEthernet")
        self.oLbCom = QtWidgets.QLabel(self.oFrameMain)
        self.oLbCom.setGeometry(QtCore.QRect(349, 0, 171, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oLbCom.sizePolicy().hasHeightForWidth())
        self.oLbCom.setSizePolicy(sizePolicy)
        self.oLbCom.setMinimumSize(QtCore.QSize(160, 30))
        self.oLbCom.setMaximumSize(QtCore.QSize(2000, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oLbCom.setFont(font)
        self.oLbCom.setFrameShape(QtWidgets.QFrame.Box)
        self.oLbCom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.oLbCom.setAlignment(QtCore.Qt.AlignCenter)
        self.oLbCom.setObjectName("oLbCom")
        self.oEntryIp0 = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryIp0.setGeometry(QtCore.QRect(110, 40, 41, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryIp0.sizePolicy().hasHeightForWidth())
        self.oEntryIp0.setSizePolicy(sizePolicy)
        self.oEntryIp0.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryIp0.setFont(font)
        self.oEntryIp0.setText("")
        self.oEntryIp0.setMaxLength(3)
        self.oEntryIp0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryIp0.setPlaceholderText("")
        self.oEntryIp0.setObjectName("oEntryIp0")
        self.oEntryPort = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryPort.setGeometry(QtCore.QRect(110, 80, 221, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryPort.sizePolicy().hasHeightForWidth())
        self.oEntryPort.setSizePolicy(sizePolicy)
        self.oEntryPort.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryPort.setFont(font)
        self.oEntryPort.setMaxLength(5)
        self.oEntryPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryPort.setClearButtonEnabled(False)
        self.oEntryPort.setObjectName("oEntryPort")
        self.oListBoxCom = QtWidgets.QComboBox(self.oFrameMain)
        self.oListBoxCom.setGeometry(QtCore.QRect(350, 40, 171, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oListBoxCom.sizePolicy().hasHeightForWidth())
        self.oListBoxCom.setSizePolicy(sizePolicy)
        self.oListBoxCom.setMinimumSize(QtCore.QSize(160, 20))
        self.oListBoxCom.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oListBoxCom.setFont(font)
        self.oListBoxCom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.oListBoxCom.setObjectName("oListBoxCom")
        self.oLbIp = QtWidgets.QLabel(self.oFrameMain)
        self.oLbIp.setGeometry(QtCore.QRect(20, 40, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oLbIp.sizePolicy().hasHeightForWidth())
        self.oLbIp.setSizePolicy(sizePolicy)
        self.oLbIp.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oLbIp.setFont(font)
        self.oLbIp.setFrameShape(QtWidgets.QFrame.Box)
        self.oLbIp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.oLbIp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.oLbIp.setObjectName("oLbIp")
        self.oLbPort = QtWidgets.QLabel(self.oFrameMain)
        self.oLbPort.setGeometry(QtCore.QRect(20, 80, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oLbPort.sizePolicy().hasHeightForWidth())
        self.oLbPort.setSizePolicy(sizePolicy)
        self.oLbPort.setMinimumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oLbPort.setFont(font)
        self.oLbPort.setFrameShape(QtWidgets.QFrame.Box)
        self.oLbPort.setFrameShadow(QtWidgets.QFrame.Raised)
        self.oLbPort.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.oLbPort.setObjectName("oLbPort")
        self.oButStartStop = QtWidgets.QPushButton(self.oFrameMain)
        self.oButStartStop.setGeometry(QtCore.QRect(20, 120, 311, 30))
        self.oButStartStop.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oButStartStop.setFont(font)
        self.oButStartStop.setObjectName("oButStartStop")
        self.oEntryIp1 = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryIp1.setGeometry(QtCore.QRect(170, 40, 41, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryIp1.sizePolicy().hasHeightForWidth())
        self.oEntryIp1.setSizePolicy(sizePolicy)
        self.oEntryIp1.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryIp1.setFont(font)
        self.oEntryIp1.setText("")
        self.oEntryIp1.setMaxLength(3)
        self.oEntryIp1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryIp1.setPlaceholderText("")
        self.oEntryIp1.setObjectName("oEntryIp1")
        self.oEntryIp2 = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryIp2.setGeometry(QtCore.QRect(230, 40, 41, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryIp2.sizePolicy().hasHeightForWidth())
        self.oEntryIp2.setSizePolicy(sizePolicy)
        self.oEntryIp2.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryIp2.setFont(font)
        self.oEntryIp2.setText("")
        self.oEntryIp2.setMaxLength(3)
        self.oEntryIp2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryIp2.setPlaceholderText("")
        self.oEntryIp2.setObjectName("oEntryIp2")
        self.oEntryIp3 = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryIp3.setGeometry(QtCore.QRect(290, 40, 41, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryIp3.sizePolicy().hasHeightForWidth())
        self.oEntryIp3.setSizePolicy(sizePolicy)
        self.oEntryIp3.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryIp3.setFont(font)
        self.oEntryIp3.setText("")
        self.oEntryIp3.setMaxLength(3)
        self.oEntryIp3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryIp3.setPlaceholderText("")
        self.oEntryIp3.setObjectName("oEntryIp3")
        self.oLbIp_2 = QtWidgets.QLabel(self.oFrameMain)
        self.oLbIp_2.setGeometry(QtCore.QRect(150, 40, 21, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oLbIp_2.sizePolicy().hasHeightForWidth())
        self.oLbIp_2.setSizePolicy(sizePolicy)
        self.oLbIp_2.setMinimumSize(QtCore.QSize(5, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oLbIp_2.setFont(font)
        self.oLbIp_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.oLbIp_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.oLbIp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.oLbIp_2.setObjectName("oLbIp_2")
        self.oLbIp_3 = QtWidgets.QLabel(self.oFrameMain)
        self.oLbIp_3.setGeometry(QtCore.QRect(210, 40, 21, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oLbIp_3.sizePolicy().hasHeightForWidth())
        self.oLbIp_3.setSizePolicy(sizePolicy)
        self.oLbIp_3.setMinimumSize(QtCore.QSize(5, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oLbIp_3.setFont(font)
        self.oLbIp_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.oLbIp_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.oLbIp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.oLbIp_3.setObjectName("oLbIp_3")
        self.oLbIp_4 = QtWidgets.QLabel(self.oFrameMain)
        self.oLbIp_4.setGeometry(QtCore.QRect(270, 40, 21, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oLbIp_4.sizePolicy().hasHeightForWidth())
        self.oLbIp_4.setSizePolicy(sizePolicy)
        self.oLbIp_4.setMinimumSize(QtCore.QSize(5, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oLbIp_4.setFont(font)
        self.oLbIp_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.oLbIp_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.oLbIp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.oLbIp_4.setObjectName("oLbIp_4")
        self.oEntryBaud = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryBaud.setGeometry(QtCore.QRect(350, 80, 171, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryBaud.sizePolicy().hasHeightForWidth())
        self.oEntryBaud.setSizePolicy(sizePolicy)
        self.oEntryBaud.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryBaud.setFont(font)
        self.oEntryBaud.setText("")
        self.oEntryBaud.setMaxLength(12)
        self.oEntryBaud.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryBaud.setPlaceholderText("")
        self.oEntryBaud.setObjectName("oEntryBaud")
        self.oEntryDataBits = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryDataBits.setGeometry(QtCore.QRect(350, 120, 51, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryDataBits.sizePolicy().hasHeightForWidth())
        self.oEntryDataBits.setSizePolicy(sizePolicy)
        self.oEntryDataBits.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryDataBits.setFont(font)
        self.oEntryDataBits.setText("")
        self.oEntryDataBits.setMaxLength(1)
        self.oEntryDataBits.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryDataBits.setPlaceholderText("")
        self.oEntryDataBits.setObjectName("oEntryDataBits")
        self.oEntryParityBits = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryParityBits.setGeometry(QtCore.QRect(410, 120, 51, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryParityBits.sizePolicy().hasHeightForWidth())
        self.oEntryParityBits.setSizePolicy(sizePolicy)
        self.oEntryParityBits.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryParityBits.setFont(font)
        self.oEntryParityBits.setText("")
        self.oEntryParityBits.setMaxLength(3)
        self.oEntryParityBits.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryParityBits.setPlaceholderText("")
        self.oEntryParityBits.setObjectName("oEntryParityBits")
        self.oEntryStopBits = QtWidgets.QLineEdit(self.oFrameMain)
        self.oEntryStopBits.setGeometry(QtCore.QRect(470, 120, 51, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oEntryStopBits.sizePolicy().hasHeightForWidth())
        self.oEntryStopBits.setSizePolicy(sizePolicy)
        self.oEntryStopBits.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oEntryStopBits.setFont(font)
        self.oEntryStopBits.setText("")
        self.oEntryStopBits.setMaxLength(3)
        self.oEntryStopBits.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.oEntryStopBits.setPlaceholderText("")
        self.oEntryStopBits.setObjectName("oEntryStopBits")
        self.gridLayout.addWidget(self.oFrameMain, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 21))
        self.menubar.setObjectName("menubar")
        self.menuinfo = QtWidgets.QMenu(self.menubar)
        self.menuinfo.setObjectName("menuinfo")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.oActExit = QtWidgets.QAction(MainWindow)
        self.oActExit.setObjectName("oActExit")
        self.oActInfo = QtWidgets.QAction(MainWindow)
        self.oActInfo.setObjectName("oActInfo")
        self.menuinfo.addAction(self.oActExit)
        self.menuAbout.addAction(self.oActInfo)
        self.menubar.addAction(self.menuinfo.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.oLbEthernet.setText(_translate("MainWindow", "Module TCP/IP Settings"))
        self.oLbCom.setText(_translate("MainWindow", "Serial Port Bind"))
        self.oLbIp.setText(_translate("MainWindow", "IP: "))
        self.oLbPort.setText(_translate("MainWindow", "PORT: "))
        self.oButStartStop.setText(_translate("MainWindow", "Start"))
        self.oLbIp_2.setText(_translate("MainWindow", "."))
        self.oLbIp_3.setText(_translate("MainWindow", "."))
        self.oLbIp_4.setText(_translate("MainWindow", "."))
        self.menuinfo.setTitle(_translate("MainWindow", "Control"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.oActExit.setText(_translate("MainWindow", "Exit"))
        self.oActInfo.setText(_translate("MainWindow", "Info"))

